kind: pipeline
type: docker
name: default

platform:
  os: linux
  ar—Åh: arm64

steps:
- name: unit test
  image: kameshsampath/drone-java-maven-plugin:v1.0.3
  pull: if-not-exists
  settings:
    maven_mirror_url: http://nexus:8081/repository/maven-public/
    goals:
    - clean 
    - test
    - -q
- name: package as jar
  image: kameshsampath/drone-java-maven-plugin:v1.0.3
  pull: if-not-exists
  settings:
    maven_mirror_url: http://nexus:8081/repository/maven-public/
    goals:
    - clean 
    - install
    - -DskipTests
    - -q

- name: push image to registry
  image: thegeeklab/drone-docker-buildx
  privileged: true
  pull: if-not-exists
  settings:
    platforms:
      - linux/arm64
      - linux/amd64
    context: .
    registry: quay.io
    username:
      from_secret: quayio_username
    password:
      from_secret: quayio_password
    purge: true
